version: '3'

services: 
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./app/:/var/www/app/
        ports: 
            - 8011:80
        networks:
            - app
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        volumes: 
            - ./app/:/var/www/app/
        networks: 
            - app
        depends_on: 
            - db

    db:
        image: mysql:5.7
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        environment: 
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: test
        ports:
            - 3341:3336
        volumes: 
            - ./mysql:/var/lib/mysql
        networks: 
            - app

    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
            - db
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        networks: 
            - app    

networks:
    app:
        